baseURL = "https://filipeamaral.me/"
disqusShortname = "felpsme"
googleAnalytics = "UA-103450981-1"
title = "Filipe Amaral"
theme = "hugo-tailwind-journal"
pygmentsCodeFences = true
pygmentsUseClasses = true
languageCode = "en-us"
publishDir = "docs"

[taxonomies]
    tag = "tags"

[permalinks]
    posts = "/posts/:title/"

[params]
    author = "Filipe Amaral"
    avatar = "images/avatar.jpeg"
    description = "I am a Full Stack Engineer specializing in Django, VueJs and AWS."
    tagline = "I am a Full Stack Engineer specializing in Django, VueJs and AWS."

